version: '3.8'

networks:
  mysql-network:

services:
  php:
    build:
      context: ./data/php
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80
    networks:
      - mysql-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gambling
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - mysql-network
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    networks:
      - mysql-network
    ports:
      - "8080:8080"
